### ISSUE TITLE
Free quota expired 

### ISSUE THREAD

**Issue by Steake** [TripleSpeeder/token-allowance-checker#124]
<img width="1242" alt="Screenshot 2020-10-06 at 22 55 46" src="https://user-images.githubusercontent.com/530040/95226445-24423e80-0827-11eb-8baa-d39799892cb7.png">

**Comment by MattiooFR** [comment]
Yup, same screen !

**Comment by TripleSpeeder** [comment]
Thank you for reporting this! It was bad timing as I was travelling, but the quota is sorted out for now :-)
