### ISSUE TITLE
Cannot choose address on Ledger

### ISSUE THREAD

**Issue by Myridium** [TripleSpeeder/token-allowance-checker#135]
There is no option to choose an address with a Ledger device. I assume it chooses the first one in the Hierarchical Determination scheme. But which key derivation path is it (e.g. Ledger or Ledger Live)? Should have the option to select a key derivation path, if not explore it dynamically like every other DApp.

**Comment by TripleSpeeder** [comment]
You can select address and derivation path by clicking on the green "Wallet: ..." button on the top bar.
