### ISSUE TITLE
Display more information about Spender address

### ISSUE THREAD

**Issue by TripleSpeeder** [TripleSpeeder/token-allowance-checker#3]
As a user I usually can not recognize which Dapp/entity is behind a spender address.
Ideally the UI would prominently show e.g. the name of the according DEX.

Obviously this will be difficult to accomplish. Things to check:
- Is there a reverse ENS entry existing for the spender address?
- Is there any third-party API that provides a mapping contract address -> Dapp/Project name?

**Comment by TripleSpeeder** [comment]
Etherscan contract API (https://etherscan.io/apis#contracts) provides contract source and name for verified contracts (method getContractSource). This could be a start.

**Comment by spaceblankey** [comment]
This is 100% necessary, I can't go chasing down all the contracts to see if I recognize them or not.  Not sure how to accomplish it though.
