### ISSUE TITLE
Unknown error "Error {}" thrown after check allowances

### ISSUE THREAD

**Issue by spaceblankey** [TripleSpeeder/token-allowance-checker#31]
A red error box with a exclamation point and the text ""Error {}". Using metamask, address is correct, on mainnet, also tried entering the ENS for that address got the same result.

**Comment by TripleSpeeder** [comment]
Thanks for the report! Can you provide the address your were looking at when the error occured? Also is there any additional error logged to the browser console?

**Comment by spaceblankey** [comment]
it is 0xa289364347bfC1912ab672425Abe593ec01Ca56E

Additional errors: 
Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
    at s.decodeParameters (index.js:239)
    at s.decodeLog (index.js:302)
    at AllowanceLister.js:150
    at Array.forEach (<anonymous>)
    at AllowanceLister.js:143
    at Array.forEach (<anonymous>)
    at AllowanceLister.js:142
    at u (runtime.js:45)
    at Generator._invoke (runtime.js:271)
    at Generator.forEach.t.<computed> [as next] (runtime.js:97)
    at n (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)
DevTools failed to parse SourceMap: chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map
DevTools failed to parse SourceMap: chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/contentscript.js.map
DevTools failed to parse SourceMap: chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/inpage.js.map

**Comment by TripleSpeeder** [comment]
Thanks @spaceblankey - Your report led to actual 2 different issues being fixed :+1:

**Comment by spaceblankey** [comment]
Yup, working now. Thank you.
